export default {
    SAVE_USER: "SAVE_USER_ACTION",
    SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
    LOGIN_USER: "LOGIN_USER_ACTION",
    LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
    DISABLE_REDIRECT: "DISABLE_REDIRECT",
    STOP_SESSION: "STOP_SESSION",
    GET_ORDERS_ACTION: "GET_ORDERS_ACTION",
    GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",
    CHANGE_PASSWORD_ACTION: "CHANGE_PASSWORD_ACTION",
    CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",

};